---
title: "Data Science in R: Project Proposal"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Overview

The proposed project aims on the analysis of a data set containing trajectory data of hum.





## Project title
Analysis of trajectory data with relation to short and long term memory experiments.


## Team
Alexander Wagner
Johannes Dambacher
Termin ausmachen

## Background and motivation

The data was recorded during a study on the impact of exploring novelty onto the learning success of children. Another constrain was the distinction between children with ADHD and children without.
For the experiment both children with ADHD and the control group had to attend the study on three different days.
On the first day the test persons got familiarized with the virtual world by spending between 10 and 20 min exploring of three worlds.
On day two the test persons had to learn 20 new vocabularies and recall them afterwards. After the recalling the test persons virtually explored another world for 10 to 20 min. The virtual worlds on day one and two were the same for some test persons and different for others.
On day three simply the variables had to be recalled by the test persons.

The data set recorded during the tests consists of the trajectory data of the 66 test persons as well as several other variables such as sex, age and others.
The trajectory data was retrieved by tracking the test persons movement within a 3d virtual Mincraft world. The sample rate was set to a tenth of a second. The data contains a time stamp and the x,y and z coordinate of the test persons avatar in the virtual world at the given time. Due to the software based digital tracking within a virtual world the sample points contain an exact time stamp and neither noise, outlier nor ambiguities or other measurement based bias.
The time spent in the virtual world should range from 10 to 20 min where the test persons could freely stop exploring the world after 10 min. Some trajectory data sets contain less than 10 min of sample points. This was caused by accident, technical failure.
The second data set contains variables such as sex, age and others as well as the number of words remembered correctly/wrongly on the first/second day, the virtual world id for day one/tow and several scores obtained using a questionnaire related to immersion, exploration behavior and similar.

## Project objectives
* Interactive visualization of the data set
* Predicting the ADHD type on basis of the trajectory data
* Impact of the novelty of the virtual world on day two on the learning success
* Impact of novelty seeking and exploitative excitability on the learning success
* Comparison/cluster analysis of the exploratory behavior of ADHD and control group
* Impact of the novelty seeking and exploitative excitability on the trajectory/exploration behavior

## Possible problems:
* Only ~50 usable data entries for trajectory analysis -> difficult to prove statistic significant
* Little comparable work on the comparison of trajectories
* Little comparable work on the feature extraction from trajectories
* Interactive data visualization and exploration




## Dataset
Vielleicht hier einen kleinen Auschnitt zeigen und darauf eingehen, wie die Daten vorverarbeitet werden (oder auch auf den Datenschutz eingehen)




## Design overview (algorithms and methods you plan to use)
* Trajectory Analysis
* Feature extraction from trajectories
* Clustering into exploitative behavior 
* Scatterplot Matrix, Correlation analysis
* Regression Lines
* Spectral analysis of trajectory data (if not to complicated)

* 3D Scatter Plot (for Trajectories)
* Regression Models
* Scatterplot Matrix
* Cluster visualisation



## Project Plan (Time plan including distribution of responsibilites and workload among team members written as weekly deadlines)

|       Week      |        Task        | Substasks | Responsible |
|:---------------:|:------------------:|-----------|:-----------:|
| 19.11. - 25.11. |Scatterplotmatrix   |           |             |
| 26.11. - 02.12. |Clustering          |           |             |
| 03.12. - 09.12. |                    |           |             |
| 10.12. - 16.12. |                    |           |             |
| 17.12. - 23.12. |                    |           |             |
| 24.12. - 30.12. |                    |           |             |
| 31.12. - 06.01. |                    |           |             |
| 07.01. - 13.01. |                    |           |             |
|                 | Submission         |           |             |
| 25.01.          | Final Presentation |           |             |

